services:
  - type: web
    name: truquetec-api
    runtime: python
    rootDir: server
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SERP_API_KEY
        sync: false
      - key: USD_TO_MXN_RATE
        value: "18.5"
